Web MVC/WebAppECartDemo/Controllers/ShoppingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppECartDemo.Models;
using WebAppECartDemo.ViewModel;

namespace WebAppECartDemo.Controllers
{
    public class ShoppingController : Controller
    {
        private ECartDBEntities1 objECartDbEntities;
        private List<ShoppingCartModel> listOfShoppingCartModels;
        public ShoppingController()
        {
            objECartDbEntities = new ECartDBEntities1();
            listOfShoppingCartModels = new List<ShoppingCartModel>();
        }
        // GET: Shopping
        public ActionResult Index()
        {
            IEnumerable<ShoppingViewModel> listOfShoppingViewModels = (from objItem in objECartDbEntities.Items
                    join
                        objCate in objECartDbEntities.Categories
                        on objItem.CategoryId equals objCate.CategoryId
                    select new ShoppingViewModel()
                    {
                        ImagePath = objItem.ImagePath,
                        ItemName = objItem.ItemName,
                        Description = objItem.Description,
                        ItemPrice = objItem.ItemPrice,
                        ItemId = objItem.ItemId,
                        Category = objCate.CategoryName,
                        ItemCode = objItem.ItemCode
                    }

                ).ToList();
            return View(listOfShoppingViewModels);
        }

        [HttpPost]
        public JsonResult Index(string ItemId)
        {
            ShoppingCartModel objShoppingCartModel = new ShoppingCartModel();
            Item objItem = objECartDbEntities.Items.Single(model => model.ItemId.ToString() == ItemId);
            if (Session["CartCounter"] != null)
            {
                listOfShoppingCartModels = Session["CartItem"] as List<ShoppingCartModel>;
            }
            if (listOfShoppingCartModels.Any(model => model.ItemId == ItemId))
            {
                objShoppingCartModel = listOfShoppingCartModels.Single(model => model.ItemId == ItemId);
                objShoppingCartModel.Quantity = objShoppingCartModel.Quantity + 1;
                objShoppingCartModel.Total = objShoppingCartModel.Quantity * (objShoppingCartModel.UnitPrice);
            }
            else
            {
                objShoppingCartModel.ItemId = ItemId;
                objShoppingCartModel.ImagePath = objItem.ImagePath;
                objShoppingCartModel.ItemName = objItem.ItemName;
                objShoppingCartModel.Quantity = 1;
                objShoppingCartModel.Total = objItem.ItemPrice;
                objShoppingCartModel.UnitPrice = objItem.ItemPrice;
                listOfShoppingCartModels.Add(objShoppingCartModel);
            }

            Session["CartCounter"] = listOfShoppingCartModels.Count;
            Session["CartItem"] = listOfShoppingCartModels;
            return Json(new {Success = true, Counter = listOfShoppingCartModels .Count}, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ShoppingCart()
        {
            listOfShoppingCartModels = Session["CartItem"] as List<ShoppingCartModel>;
            return View(listOfShoppingCartModels);
        }

        [HttpPost]
        public ActionResult AddOrder()
        {
            int OrderId = 0;
            listOfShoppingCartModels = Session["CartItem"] as List<ShoppingCartModel>;
            Order orderObj = new Order()
            {
                OrderDate = DateTime.Now,
                OrderNumber = String.Format("{0:ddmmyyyyHHmmsss}",DateTime.Now)
            };
            objECartDbEntities.Orders.Add(orderObj);
            objECartDbEntities.SaveChanges();
            OrderId = orderObj.OrderId;

            foreach (var item in listOfShoppingCartModels)
            {
                OrderDetail objOrderDetail = new OrderDetail();
                objOrderDetail.Total = item.Total;
                /*objOrderDetail.ItemId = item.ItemId;*/
                objOrderDetail.OrderId = OrderId;
                objOrderDetail.Quantity = item.Quantity;
                objOrderDetail.UnitPrice = item.UnitPrice;
                objECartDbEntities.OrderDetails.Add(objOrderDetail);
                objECartDbEntities.SaveChanges();
            }

            Session["CartItem"] = null;
            Session["CartCounter"] = null;
            return RedirectToAction("Index");
        }

        public ActionResult RemoveItem(string name)
        {
            listOfShoppingCartModels = Session["CartItem"] as List<ShoppingCartModel>;
            ShoppingCartModel objShoppingCartModel = listOfShoppingCartModels.Single(model => model.ItemName == name);
            listOfShoppingCartModels.Remove(objShoppingCartModel);
            Session["CartItem"] = listOfShoppingCartModels;
            Session["CartCounter"] = listOfShoppingCartModels.Count;
            return RedirectToAction("ShoppingCart");
        }

        //public ActionResult UpdateItem(string name, string quantity) 
        //{
        //    listOfShoppingCartModels = Session["CartItem"] as List<ShoppingCartModel>;
        //    ShoppingCartModel objShoppingCartModel = listOfShoppingCartModels.Single(model => model.ItemName == name);
        //    objShoppingCartModel.Quantity = Convert.ToInt32(quantity);
        //    objShoppingCartModel.Total = objShoppingCartModel.Quantity * objShoppingCartModel.UnitPrice;
        //    Session["CartItem"] = listOfShoppingCartModels;
        //    /*Session["CartCounter"] = listOfShoppingCartModels.Count;*/
        //    return RedirectToAction("ShoppingCart");

        //}

        [HttpPost]
        public ActionResult UpdateItem(ShoppingCartModel model)
        {
            listOfShoppingCartModels = Session["CartItem"] as List<ShoppingCartModel>;
            ShoppingCartModel objShoppingCartModel = listOfShoppingCartModels.Single(m => m.ItemName == model.ItemName);
            objShoppingCartModel.Quantity = model.Quantity;
            objShoppingCartModel.Total = objShoppingCartModel.Quantity * objShoppingCartModel.UnitPrice;
            Session["CartItem"] = listOfShoppingCartModels;
            /*Session["CartCounter"] = listOfShoppingCartModels.Count;*/
            return RedirectToAction("ShoppingCart");

        }




    }
}

Web MVC/WebAppECartDemo/Views/Shopping/Index.cshtml
@model IEnumerable<WebAppECartDemo.ViewModel.ShoppingViewModel>
@{
    ViewBag.Title = "Index";
}

<script type="text/javascript">
    function AddToCart(item) {
        var itemId = $(item).attr("itemid");
        var formData = new FormData();
        formData.append("ItemId", itemId);

        $.ajax({
            async: true,
            type: 'POST',
            contentType: false,
            processData: false,
            data: formData,
            url: '/Shopping/Index',
            success: function(data) {
                if (data.Success) {
                    $("#cartItem").text("Cart(" + data.Counter + ")");
                }
            },
            error: function() {
                alert("There is some problem.");
            }
        });
    }
</script>
<div class="container">
    <h2 class="text-center">Product List</h2>
    @foreach (var item in Model)
    {
        <div class="col-md-4" style="border: 2px solid black">
            <div style="text-align: center; border-bottom: 2px solid maroon">
                <h3>@item.ItemName</h3>
            </div>
            <div>
                <div class="col-md-8">
                    <img src="@Url.Content(@item.ImagePath)" width="150px" height="150px" />
                </div>
                <div class="col-md-4" style="text-align: left">
                    <b>@item.Description</b>
                </div>
            </div>

            <div class="col-md-8" style="font-size: 18px; border-top: 2px solid maroon; padding: 2px">
                <b>@item.ItemPrice.ToString("#,##0.00 Dong")</b>
            </div>
            <div class="col-md-4" style="text-align: right; margin-bottom: 10px; border-top: 2px solid maroon; padding: 2px">
                <input type="button" name="AddToCart" value="Add to Cart" class="btn btn-primary" itemid="@item.ItemId" id="btnAddToCart" onclick="AddToCart(this)" />
            </div>

        </div>
    }
</div>

Web MVC/WebAppECartDemo/Views/Shopping/ShoppingCart.cshtml
@model IEnumerable<WebAppECartDemo.ViewModel.ShoppingCartModel>
@{
    ViewBag.Title = "ShoppingCart";
    decimal TotalAmount = 0.00M;
}

<h2>ShoppingCart</h2>




<table class="table-condensed" style="width: 100%">
    @if (Model != null)
    {
        foreach (var item in Model)
        {
            using (Html.BeginForm("UpdateItem", "Shopping", FormMethod.Post))
            {
                TotalAmount += item.Total;
                <tr>
                    <td>
                        <img src="@Url.Content(item.ImagePath)" height="50px" width="50px" class="img-rounded" />
                    </td>
                    <td>
                        @item.ItemName
                        @Html.HiddenFor(model => model.Single(a => a.ItemName == item.ItemName).ItemName)
                    </td>
                    <td style="text-align: right">
                        @Html.TextBoxFor(model => model.Single(a => a.ItemName == item.ItemName).Quantity)
                        @Html.ValidationMessageFor(model => model.Single(a => a.ItemName == item.ItemName).Quantity)
                    </td>
                    <td style="text-align: right">
                        @item.UnitPrice.ToString("#,##0.00")
                    </td>
                    <td style="text-align: right">
                        @item.Total.ToString("#,##0.00")
                    </td>

                    <td>
                        @Html.ActionLink("Remove Item", "RemoveItem", "Shopping", new { name = item.ItemName }, null)
                    </td>

                    <td>
                        <button type="submit"> Update Quantity </button>
                    </td>
                </tr>
            }
        }
    }



    @using (Html.BeginForm("AddOrder", "Shopping", FormMethod.Post))
    {
        <tr style="border-top: 2px solid maroon">
            <td colspan="4" style="text-align: right">
                <h3>Total Amount:</h3>
            </td>
            <td style="text-align: right">
                <h3>@TotalAmount.ToString("#,##0.00")</h3>
            </td>
        </tr>

        <tr style = "border-top: 2px solid maroon" >
        <td colspan="4" style="text-align: right;">
            <h3 style ="margin-bottom: 9rem; margin-right: 62.4rem ">Payment method:</h3>
        </td>
        <td style="text-align: right">
            <input type="radio" id="cash" name="payment" value="Cash" checked="checked">
            <img src="https://img.icons8.com/color/48/null/cash-in-hand.png" />
            <label for="cash">Cash</label><br>
            <input type="radio" style="margin-right: 1rem" id="Momo" name="payment" value="Momo">
            <img src="https://play-lh.googleusercontent.com/dQbjuW6Jrwzavx7UCwvGzA_sleZe3-Km1KISpMLGVf1Be5N6hN6-tdKxE5RDQvOiGRg" height="36px" width="36px"
            <label for="momo"  > <b> Momo</b></label><br>
            <input type="radio" id="creditcard" name="payment" value="CreditCard">
            <img src="https://img.icons8.com/emoji/48/null/credit-card-emoji.png" />
            <label for="creditcard">Credit Card</label>
        </td>
        </tr>

        <tr style="text-align: right">
            <td colspan="5">
                <input type="submit" value="Save" name="Save" class="btn btn-primary" id="SaveOrder" />
            </td>
        </tr>

        <tr style="text-align: center">
            <td colspan="5">
                @Html.ActionLink("Back to Shopping", "Index", "Shopping")
            </td>
        </tr>


    }
</table>